// Generates a standalone React component file for a form — the "Deploy"
// button in BuilderScreen.jsx. FillScreen.jsx's `form` prop (rather than
// `formId`) is what makes this genuinely portable: the generated file
// carries the form's data with it, so it renders correctly in a project
// that's never seeded this form into its own IndexedDB.

function toPascalCase(text) {
  const words = text
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
  const pascal = words.map((word) => word[0].toUpperCase() + word.slice(1)).join('')
  return pascal || 'Form'
}

export function suggestedComponentFilename(form) {
  return `${toPascalCase(form.title)}.jsx`
}

export function generateFormComponent(form) {
  const componentName = toPascalCase(form.title)
  const formJson = JSON.stringify(form, null, 2)

  return `import { FillScreen, BrandProvider, ThemeProvider } from 'form-builder-kit'
import 'form-builder-kit/style.css'

// Generated by Form Designer from "${form.title}" — edits made directly to
// this file won't round-trip back into the builder; re-deploy to update it.
//
// Responses submit to this browser's local storage by default. To send them
// to a real backend instead, call configureBackend({ apiBaseUrl }) once
// elsewhere in your app before this component mounts — see
// form-builder-kit's README ("Publishing across a subdomain").
const form = ${formJson}

export default function ${componentName}() {
  return (
    <ThemeProvider>
      <BrandProvider brand={form.brand}>
        <FillScreen form={form} />
      </BrandProvider>
    </ThemeProvider>
  )
}
`
}
